interface ReportData {
  jobTitle: string;
  company: string;
  overallScore: number;
  skillScores: { name: string; score: number }[];
  strengths: string[];
  improvements: string[];
  feedback: { question: string; response: string; score: number }[];
}

export function generateReportPDF(data: ReportData): void {
  // Create HTML content for the report
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <title>Interview Report - ${data.jobTitle}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
    .header { text-align: center; border-bottom: 2px solid #6366f1; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { color: #6366f1; margin-bottom: 5px; }
    .header p { color: #666; }
    .score-section { background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; padding: 30px; border-radius: 12px; text-align: center; margin-bottom: 30px; }
    .score-section .score { font-size: 48px; font-weight: bold; }
    .score-section .label { opacity: 0.9; }
    .section { margin-bottom: 30px; }
    .section h2 { color: #6366f1; border-bottom: 1px solid #e5e7eb; padding-bottom: 10px; }
    .skill-bar { background: #f3f4f6; border-radius: 8px; height: 24px; margin: 10px 0; overflow: hidden; }
    .skill-bar-fill { background: #6366f1; height: 100%; border-radius: 8px; }
    .skill-label { display: flex; justify-content: space-between; margin-bottom: 4px; }
    ul { padding-left: 20px; }
    li { margin: 8px 0; color: #4b5563; }
    .feedback-item { background: #f9fafb; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 4px solid #6366f1; }
    .feedback-score { display: inline-block; background: #6366f1; color: white; padding: 4px 12px; border-radius: 20px; font-size: 14px; }
    .footer { text-align: center; color: #9ca3af; font-size: 12px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <div class="header">
    <h1>InterviewAI Report</h1>
    <p>${data.jobTitle} at ${data.company}</p>
    <p>Generated on ${new Date().toLocaleDateString()}</p>
  </div>

  <div class="score-section">
    <div class="score">${data.overallScore}%</div>
    <div class="label">Overall Performance Score</div>
  </div>

  <div class="section">
    <h2>Skill Breakdown</h2>
    ${data.skillScores.map(skill => `
      <div class="skill-label">
        <span>${skill.name}</span>
        <span>${skill.score}%</span>
      </div>
      <div class="skill-bar">
        <div class="skill-bar-fill" style="width: ${skill.score}%"></div>
      </div>
    `).join('')}
  </div>

  <div class="section">
    <h2>Strengths</h2>
    <ul>
      ${data.strengths.map(s => `<li>✓ ${s}</li>`).join('')}
    </ul>
  </div>

  <div class="section">
    <h2>Areas for Improvement</h2>
    <ul>
      ${data.improvements.map(i => `<li>⚠ ${i}</li>`).join('')}
    </ul>
  </div>

  <div class="section">
    <h2>Question-by-Question Feedback</h2>
    ${data.feedback.map(f => `
      <div class="feedback-item">
        <strong>${f.question}</strong>
        <span class="feedback-score">${f.score}%</span>
        <p>${f.response}</p>
      </div>
    `).join('')}
  </div>

  <div class="footer">
    <p>This report was generated by InterviewAI - AI-Powered Interview Platform</p>
    <p>© ${new Date().getFullYear()} InterviewAI. All rights reserved.</p>
  </div>
</body>
</html>
  `;

  // Create a blob and download
  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  // Open in new window for printing
  const printWindow = window.open(url, '_blank');
  if (printWindow) {
    printWindow.onload = () => {
      printWindow.print();
    };
  }
  
  // Cleanup
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
